title: 郑旭刚的学术主页
page-top-title: 郑旭刚 (Xugang Zheng)
top-section-bg-text: 劳动经济学 · 城镇化 · 数字经济 · 劳动力市场
home-subtitle: 郑旭刚&nbsp;|&nbsp;Xugang Zheng
copyright-text: '&copy; Xugang Zheng 2026. All Rights Reserved.'
