title: Xugang Zheng | Academic Homepage
page-top-title: 郑旭刚 (Xugang Zheng)
top-section-bg-text: Labor Economics · Urbanization · Migrant Workers
home-subtitle: 郑旭刚&nbsp;|&nbsp;Xugang Zheng
copyright-text: '&copy; Xugang Zheng 2026. All Rights Reserved.'
